groups:
- name: kafka-alerts
  rules:
  - alert: KafkaBrokerDown
    expr: up{job="kafka"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Kafka broker down"
      description: "Kafka broker {{ $labels.instance }} is down"
